[package]
name = "garch"
version = "0.1.0"
authors = ["Francis Tseng <accounts@frnsys.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
rustimization = "0.1.1"
finitediff = "0.1.2"
